# Examples for labeler Github Action [https://github.com/marketplace/actions/labeler]
# 
# Add 'label1' to any changes within 'example' folder or any subfolders
#label1:
#- example/**/*

# Add 'label2' to any file changes within 'example2' folder
#label2: example2/*

# Add 'repo' label to any root file changes
#repo:
#- '*'

# Add '@domain/core' label to any change within the 'core' package
#@domain/core:
#- package/core/*
#- package/core/**/*

# Add 'test' label to any change to *.spec.js files within the source dir
#test:
#- src/**/*.spec.js

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
#source:
#- any: ['src/**/*', '!src/docs/*']

# Add 'frontend` label to any change to *.js files as long as the `main.js` hasn't changed
#frontend:
#- any: ['src/**/*.js']
#  all: ['!src/main.js']

GraphQL:
- app/graphql/**/*
