---
extends:
  - '@commitlint/config-conventional'
parserPreset:
  parserOpts:
    headerPattern: '^(\w*)\((\w*)\):\s(\w+-[0-9]+)\s(.*)$'
    headerCorrespondence:
      - 'type'
      - 'scope'
      - 'ticket'
      - 'subject'
