---
extends:
  - '@commitlint/config-conventional'
parserPreset:
  parserOpts:
    headerPattern: '^(\w*)\((\w*)\):\s(\w+-[0-9]+\s)?(.*)$'
    headerCorrespondence:
      - 'type'
      - 'scope'
      - 'ticket'
      - 'subject'
rules:
  type-enum:
    - 2
    - always
    -
      - build
      - chore
      - ci
      - cleanup
      - dev
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
  scope-enum:
    - 2
    - always
    -
      - Dockerfile
      - clowder
      - Rails
      - RBAC
      - deps
      - Konflux
      - API
      - OpenAPI
      - logging
      - metrics
      - floorist
      - Redis
      - DB
      - SSG
      - Tailoring
      - README
      - GitHub
