require:
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.2
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'test/fixtures/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'lib/prometheus/**/*'

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['included', 'class_methods', 'GraphQL::ObjectType.define']
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
