require:
  - rubocop-rails

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.1
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'test/fixtures/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'lib/prometheus/**/*'

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  AllowedMethods: ['included', 'class_methods', 'GraphQL::ObjectType.define']
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  EmptyLineBetweenClassDefs: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Security/IoMethods:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/FileWrite:
  Enabled: false

Style/MapToHash:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/StringConcatenation:
  Mode: conservative

Style/RedundantAssignment:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Rails/IndexWith:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/ActionControllerTestCase:
  Enabled: false

Rails/ActiveRecordCallbacksOrder:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/Pluck:
  Enabled: false

Rails/PluckInWhere:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/Pick:
  Enabled: false
