inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.2
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'test/fixtures/**/*'
    - 'Rakefile'
    - 'Gemfile'

Rails:
  Enabled: true

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
