GraphQL::Cache.configure do |config|
  config.namespace = 'compliance' # Cache key prefix for keys generated by graphql-cache
  config.cache     = Rails.cache      # The cache object to use for caching
  config.logger    = Rails.logger     # Logger to receive cache-related log messages
  config.expiry    = 15552000         # 6 months (in seconds)
end

module GraphQL
  module Cache
    module DeconstructorExtensions
      def perform
        return raw.value if method == 'lazy'
        super
      end
    end

    class Deconstructor
      prepend DeconstructorExtensions
    end
  end
end
