{
 "title": "Compliance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "rds_datasource", "label": "rds_datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Current values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "sum(increase(rails_requests_total{application=\"compliance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "2xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(rails_requests_total{application=\"compliance\",status=~\"2.*\"}[$__range])) / sum(increase(rails_requests_total{application=\"compliance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Backend restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{pod=~\"compliance-backend-.*\"}))"
    }
   ]
  },
  {
   "title": "Consumer restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{pod=~\"compliance-consumer-.*\"}))"
    }
   ]
  },
  {
   "title": "Import-remediations restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{pod=~\"compliance-import-remediations-.*\"}))"
    }
   ]
  },
  {
   "title": "Import-ssg restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_status_restarts_total{pod=~\"compliance-import-ssg-.*\"}))"
    }
   ]
  },
  {
   "title": "Inventory restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{pod=~\"compliance-inventory-.*\"})"
    }
   ]
  },
  {
   "title": "Prometheus-exporter restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{pod=~\"compliance-prometheus-exporter-.*\"})"
    }
   ]
  },
  {
   "title": "5xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(rails_requests_total{application=\"compliance\",status=~\"5.*\"}[$__range])) / sum(increase(rails_requests_total{application=\"compliance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "4xx ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(rails_requests_total{application=\"compliance\",status=~\"4.*\"}[$__range])) / sum(increase(rails_requests_total{application=\"compliance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Redis restarts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "format": "none",
   "valueName": "delta",
   "targets": [
    {
     "expr": "max(kube_pod_container_status_restarts_total{pod=~\"compliance-redis-.*\"})"
    }
   ]
  },
  { "title": "Golden signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rails_requests_total{application=\"compliance\",status=~\"[0-9]{3}\"}[$interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(rate(rails_request_duration_seconds_sum{application=\"compliance\"}[$interval])) / sum(rate(rails_request_duration_seconds_bucket{application=\"compliance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "CPU consumed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"compliance-.*\"}[$interval])) by (container)/ sum(kube_pod_container_resource_limits{resource=\"cpu\",pod=~\"compliance-.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory consumed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{pod=~\"compliance-.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "Advanced", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Containers restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{pod=~\"compliance-.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_topic_sum_lag{topic=\"platform.inventory.events\", group=\"complianceinventory-events-consumer\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "GraphQL Median Performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(graphql_field_resolve_runtime_seconds_bucket{application=\"compliance\"}) by (type,field,le))",
     "legendFormat": "{{type}}.{{field}}"
    }
   ]
  },
  {
   "title": "GraphQL 99th percentile performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(graphql_field_resolve_runtime_seconds_bucket{application=\"compliance\"}) by (type,field,le))",
     "legendFormat": "{{type}}.{{field}}"
    }
   ]
  },
  {
   "title": "Latest Page Median Performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rails_request_duration_seconds_bucket{application=\"compliance\",action=\"query\",controller=\"graphql\"}) by (le)) * 1000",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rails_view_runtime_seconds_bucket{application=\"compliance\",action=\"query\",controller=\"graphql\"}) by (le)) * 1000",
     "legendFormat": "view"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rails_db_runtime_seconds_bucket{application=\"compliance\",action=\"query\",controller=\"graphql\"}) by (le)) * 1000",
     "legendFormat": "sql"
    }
   ]
  },
  {
   "title": "Latest Page 99th Percentile Performance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rails_request_duration_seconds_bucket{application=\"compliance\",action=\"query\",controller=\"graphql\"}) by (le)) * 1000",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rails_view_runtime_seconds_bucket{application=\"compliance\",action=\"query\",controller=\"graphql\"}) by (le)) * 1000",
     "legendFormat": "view"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rails_db_runtime_seconds_bucket{application=\"compliance\",action=\"query\",controller=\"graphql\"}) by (le)) * 1000",
     "legendFormat": "sql"
    }
   ]
  },
  {
   "title": "Database items (1)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(compliance_total_systems)", "legendFormat": "systems" },
    { "expr": "sum(compliance_total_accounts)", "legendFormat": "accounts" }
   ]
  },
  {
   "title": "Database items (2)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "sum(compliance_total_policies)", "legendFormat": "policies" }
   ]
  },
  {
   "title": "Sidekiq Job Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sidekiq_job_runtime_seconds_bucket{application=\"compliance\"}[$interval])) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Sidekiq Job Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(sidekiq_jobs_executed_total{application=\"compliance\"}[$interval])) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "RDS data capacity usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rdsosmetrics_fileSys_usedPercent{exported_instance=\"compliance-prod\"}) by (mount_point)",
     "legendFormat": "{{mount_point}}"
    }
   ]
  },
  {
   "title": "RDS CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(rdsosmetrics_processList_cpuUsedPc{exported_instance=\"compliance-prod\"}, \"db_user\", \"$1\", \"name\", \"postgres: ([^ ]+) .+\")) by (db_user)",
     "legendFormat": "{{db_user}}"
    },
    {
     "expr": "sum(rdsosmetrics_processList_cpuUsedPc{exported_instance=\"compliance-prod\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "RDS memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rdsosmetrics_memory_total{exported_instance=\"compliance-prod\"})",
     "legendFormat": "total memory"
    },
    {
     "expr": "sum(rdsosmetrics_memory_free{exported_instance=\"compliance-prod\"})",
     "legendFormat": "free memory"
    },
    {
     "expr": "sum(rdsosmetrics_memory_dirty{exported_instance=\"compliance-prod\"})",
     "legendFormat": "dirty memory"
    },
    {
     "expr": "sum(rdsosmetrics_memory_active{exported_instance=\"compliance-prod\"})",
     "legendFormat": "active memory"
    }
   ]
  },
  {
   "title": "RDS memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_one{exported_instance=\"compliance-prod\"})",
     "legendFormat": "Load Avg 1 min"
    },
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_five{exported_instance=\"compliance-prod\"})",
     "legendFormat": "Load Avg 5 min"
    },
    {
     "expr": "sum(rdsosmetrics_loadAverageMinute_fifteen{exported_instance=\"compliance-prod\"})",
     "legendFormat": "Load Avg 15 min"
    }
   ]
  },
  { "title": "Business metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Successfully parsed reports",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Reports" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(sidekiq_jobs_executed_total{application=\"compliance\",worker=\"ParseReportJob\"}[$interval])) OR on() vector(0)) - (sum(increase(sidekiq_jobs_failed_total{application=\"compliance\",worker=\"ParseReportJob\"}[$interval])) OR on() vector(0))",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Reports failed to upload",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "Reports" }
   ],
   "targets": [
    {
     "expr": "sum(increase(sidekiq_jobs_failed_total{application=\"compliance\",worker=\"ParseReportJob\"}[$interval])) OR on() vector(0)",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Total number of systems reporting by OS version",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 70 },
   "format": "string",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(compliance_total_systems_by_os) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Number of client systems reporting by OS version",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 70 },
   "format": "string",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(compliance_client_systems_by_os) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Total number of policies by OS major version",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 76 },
   "format": "string",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(compliance_total_policies_by_os_major) by (version)",
     "legendFormat": "RHEL {{ version }}"
    }
   ]
  },
  {
   "title": "Number of client policies by OS major version",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 76 },
   "format": "string",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(compliance_client_policies_by_os_major) by (version)",
     "legendFormat": "RHEL {{ version }}"
    }
   ]
  },
  {
   "title": "Number of policies with 50 or more systems",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(compliance_total_50plus_policies)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(compliance_client_50plus_policies)",
     "legendFormat": "Client"
    }
   ]
  },
  {
   "title": "Number of accounts with one or more policies having 50 or more systems",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 82 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(compliance_total_accounts_with_50plus_hosts_per_policy)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(compliance_client_accounts_with_50plus_hosts_per_policy)",
     "legendFormat": "Client"
    }
   ]
  },
  {
   "title": "Systems covered by at least one policy (current)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(compliance_total_systems)", "legendFormat": "Total" },
    { "expr": "sum(compliance_client_systems)", "legendFormat": "Client" }
   ]
  },
  {
   "title": "Systems covered by at least one policy (trend)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(compliance_total_systems)", "legendFormat": "Total" },
    { "expr": "sum(compliance_client_systems)", "legendFormat": "Client" }
   ]
  },
  {
   "title": "Top 4 most used profiles by accounts",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "topk(4, sum(compliance_total_policies_by_account) by (ref_id))",
     "legendFormat": "{{ ref_id }}"
    }
   ]
  },
  {
   "title": "Top 4 most used profiles by client accounts",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "topk(4, sum(compliance_client_policies_by_account) by (ref_id))",
     "legendFormat": "{{ ref_id }}"
    }
   ]
  },
  {
   "title": "Top 4 most used profiles by hosts",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "topk(4, sum(compliance_total_policies_by_host) by (ref_id))",
     "legendFormat": "{{ ref_id }}"
    }
   ]
  },
  {
   "title": "Top 4 most used profiles by client hosts",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 100 },
   "targets": [
    {
     "expr": "topk(4, sum(compliance_client_policies_by_host) by (ref_id))",
     "legendFormat": "{{ ref_id }}"
    }
   ]
  }
 ]
}