apiVersion: v1
kind: Template
metadata:
  name: builder-jenkins-slave-compliance-backend

parameters:
- name: NAME
  displayName: Name
  required: true
  value: jenkins-slave-base-centos7-ruby25-openscap

objects:

- kind: BuildConfig
  metadata:
    name: "${NAME}"
  spec:
    failedBuildsHistoryLimit: 5
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}"
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/RedHatInsights/compliance-backend
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: openshift/Jenkins/Dockerfile
      type: Docker
    successfulBuildsHistoryLimit: 5

- kind: ImageStream
  metadata:
    generation: 1
    name: "${NAME}"
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: "docker-registry.default.svc:5000/jenkins/${NAME}:latest"
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
