apiVersion: v1
kind: Pod
metadata:
  labels:
    name: compliance-backend-jenkins-slave
spec:
  containers:
  - env:
    - name: POSTGRESQL_USER
      value: compliance_user
    - name: POSTGRESQL_PASSWORD
      value: compliance_password
    - name: POSTGRESQL_ADMIN_PASSWORD
      value: db_admin_password
    - name: POSTGRESQL_DATABASE
      value: compliance
    image: registry.access.redhat.com/rhscl/postgresql-10-rhel7
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /usr/libexec/check-container
        - --live
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: postgresql
    readinessProbe:
      exec:
        command:
        - /usr/libexec/check-container
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
  - env:
    - name: DATABASE_SERVICE_NAME
      value: compliance-db
    - name: COMPLIANCE_DB_SERVICE_HOST
      value: localhost
    - name: POSTGRESQL_USER
      value: compliance_user
    - name: POSTGRESQL_PASSWORD
      value: compliance_password
    - name: POSTGRESQL_ADMIN_PASSWORD
      value: db_admin_password
    - name: POSTGRESQL_DATABASE
      value: compliance
    - name: SECRET_KEY_BASE
      value: secret_key_base
    - name: RAILS_ENV
      value: test
    image: jenkins-slave-rhel7-ruby25-openscap:latest
    name: jnlp
    args:
      - "$(JENKINS_SECRET)"
      - "$(JENKINS_NAME)"
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
  dnsPolicy: ClusterFirst
