name: Regular base image update check
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          persist-credentials: false
      - name: Install skopeo
        run: sudo apt-get install -y skopeo
      - name: Fetch latest base image digest
        run: |
          base_name=$(grep -Po '(?<=FROM )[^\s@]+(?=@)' Dockerfile | head -1)
          new_digest=$(skopeo inspect "docker://$base_name" | jq .Digest --raw-output)
          sed -i "s|FROM ${base_name}@sha256:[a-f0-9]*|FROM ${base_name}@${new_digest}|g" Dockerfile
      - name: Open or update pull request if digest changed
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          title: 'chore(image): update base image'
          branch: automation/base-image
          commit-message: 'chore(image): update and rebuild image'
          committer: 'Update-a-Bot <insights@redhat.com>'
          author: 'Update-a-Bot <insights@redhat.com>'
          sign-commits: true
