name: Regular base image update check
on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - name: Install skopeo
        run: sudo apt-get install -y skopeo
      - name: Fetch latest base image digest
        run: |
          base=$(grep -Po '(?<=FROM )([^\s]*)(?= AS build)' Dockerfile)
          skopeo inspect "docker://$base" | jq .Digest --raw-output > .baseimagedigest
          docker run --rm -u 0 quay.io/cloudservices/compliance-backend:latest sh -c \
            'microdnf update -y $(cat /opt/installedpackages) > /dev/null; rpm -q $(cat /opt/installedpackages) | sort | sha256sum | cut -d " " -f 1' \
            >> .baseimagedigest
      - name: Open or update pull request if digest changed
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          title: 'chore(image): update base image'
          branch: automation/base-image
          commit-message: 'chore(image): update and rebuild image'
          committer: 'Update-a-Bot <insights@redhat.com>'
          author: 'Update-a-Bot <insights@redhat.com>'
          sign-commits: true
