name: Regular Ruby and Bundler version update check
on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"

jobs:
  update-ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Fetch latest Ruby version from base image
        timeout-minutes: 10
        run: |
          base=$(grep -Po '(?<=FROM )([^\s]*)(?= AS build)' Dockerfile)
          docker run --rm -u 0 "${base}":latest sh -c "
            microdnf module enable -y ruby:3.3 > /dev/null;
            microdnf repoquery ruby --info | grep Version | awk '{ print \$3 }' | head -1 > .ruby-version;
            cat .ruby-version" > .ruby-version
      - name: Open or update pull request if Ruby version changed
        uses: peter-evans/create-pull-request@v8
        with:
          title: 'chore(devel): update .ruby-version'
          branch: automation/ruby-version
          commit-message: 'chore(devel): update .ruby-version'
          committer: 'Update-a-Bot <insights@redhat.com>'
          author: 'Update-a-Bot <insights@redhat.com>'
          sign-commits: true
  update-bundler:
    runs-on: ubuntu-latest
    env:
      BUNDLE_FORCE_RUBY_PLATFORM: true
      BUNDLE_BUILD__FFI: "--enable-system-libffi"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          bundler: latest
      - name: Update Bundler to latest version
        run: bundle config set frozen false && bundle update --bundler
      - name: Open or update pull request if Bundler version changed
        uses: peter-evans/create-pull-request@v8
        with:
          title: 'chore(deps): update bundler version'
          branch: automation/bundler-version
          commit-message: 'chore(deps): update bundler version'
          committer: 'Update-a-Bot <insights@redhat.com>'
          author: 'Update-a-Bot <insights@redhat.com>'
          sign-commits: true
